# Generated by Django 4.0.1 on 2022-03-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_article_subcategory_delete_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='visibility',
            field=models.BooleanField(),
        ),
    ]
